FROM node:14-alpine as build

WORKDIR /fronted

ENV PATH /fronted/node_modules/.bin:$PATH

COPY package*.json ./

RUN npm install --silent

RUN npm install react-scripts@3.4.3 -g --silent

COPY . . 

RUN npm run build

FROM nginx:alpine
WORKDIR /fronted
COPY --from=build /fronted/build /usr/share/nginx/html
COPY --from=build /fronted .
RUN apk update
RUN apk upgrade
RUN apk add nodejs
RUN apk add npm
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]